### ISSUE TITLE
Setting minSNP size, minGroup, minParent to a large number within a dataset causes program to crash

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#1]
I have a dataset of 99 sequences of relatively low sequence diversity and have found that setting a fairly large number in relationship to the sample ie. 50 on these parameters will cause a crash with the following error. 

Traceback (most recent call last):
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 991, in <module>
    main()
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 986, in main
    tile_generator(args.reference, args.in_vcf, numerical_parameters, groups, args.outdir)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 921, in tile_generator
    codes.write(f"{biohansel_codes.index[i]} : {biohansel_codes.values[i, -1]}\n")
IndexError: index -1 is out of bounds for axis 1 with size 0

**Comment by almene** [comment]
This error is currently partially patched.  Before attempting to print the scheme it checks to make sure that the data frame isn't empty

**Comment by almene** [comment]
Should be resolved, checks have been put in place to prevent illogical numbers
