### ISSUE TITLE
__main__.py, index out of range error

### ISSUE THREAD

**Issue by schonfju** [almene/schemeDev#11]
The current build of bioCanon crashes and reports an index out of range error.  The problem stems from lines 980, and 981.  The most recent commit modified line 980 to be    
'for i in range(0, len(leaves)):' instead of     'for i in range(0, len(leaves) - 1):'.  This seems to be the source of the problem.

If you need my exact inputs to reproduce the error just let me know and I can provide them. 

Error Message
-----------------
Traceback (most recent call last):
  File "/home/schonfju/miniconda/envs/biocanon-dev/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/schonfju/miniconda/envs/biocanon-dev/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/schonfju/Research/schemeDev/bioCanon/__main__.py", line 1133, in <module>
    main()
  File "/home/schonfju/Research/schemeDev/bioCanon/__main__.py", line 1128, in main
    tile_generator(args.reference, args.in_vcf, numerical_parameters, groups, args.outdir)
  File "/home/schonfju/Research/schemeDev/bioCanon/__main__.py", line 982, in tile_generator
    if len(biohansel_codes.values[i]) == 0:
IndexError: index 99 is out of bounds for axis 0 with size 99

**Comment by almene** [comment]
Line has been reverted to previous function non-typo version
