### ISSUE TITLE
User supplied groups error: empty internal columns but format correct

### ISSUE THREAD

**Issue by jrober84** [almene/schemeDev#8]
[data.zip](https://github.com/almene/schemeDev/files/4252087/data.zip)
I ran the following command

python3 -m bioCanon --in_vcf __snippy_SRR3736530/core.vcf --group_info  __snippy_SRR3736530/epi_groups.txt --reference __supplemental_material/SRR3736530.fasta --min_snps 1 --min_members 1 --min_parent 1 --outdir bio_cannon_epi_groups

and obtained an error about the format of the tsv file but it adheres to the specification in the Readme

Undefined taxa break the tool when you have a set of taxa which have the following format:
A 1 1.1
B 1 1.2
C 1

Traceback (most recent call last):
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 991, in <module>
    main()
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 986, in main
    tile_generator(args.reference, args.in_vcf, numerical_parameters, groups, args.outdir)
  File "/home/CSCScience.ca/jarobert/.conda/envs/biocannon/lib/python3.6/site-packages/bioCanon/__main__.py", line 921, in tile_generator
    codes.write(f"{biohansel_codes.index[i]} : {biohansel_codes.values[i, -1]}\n")
IndexError: index -1 is out of bounds for axis 1 with size 0

**Comment by almene** [comment]
Altered user group info file format
